### PR TITLE
More Config Options + Solidifier Support

### PR DESCRIPTION
**Pull request by Muramasa-**
List of Additions:

Added alternate Solidifier recipes (disabled by default).
Config for enabling/disabling ingot to shards.
Config for enabling/disabling shard to tool part.
Config for enabling/disabling Extruder recipes.
Config for enabling/disabling Solidifier recipes.
Config for energy consumption multiplier.

### CODE REVIEW

**Comment by Vexatos** [comment]
Closes #17.

**Comment by Vexatos** [comment]
Thanks! I will change a few things and fix the phrasing, but it does look fine.

**Comment by Muramasa-** [comment]
No problem!

**Comment by Vexatos** [comment]
Should be in version 1.0.9 of TGregworks. Go give it a try.

**Pull request merged**
